import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp,mkdir,readFile,writeFile,realpath,rm,symlink,readlink,lstat } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { independentDropIn,installOwnedReferences,removeOwnedReferences,ownedReferences,writePrivateJson } from '../../deploy/site/first-cutover-files.mjs'
async function fixture(t){const root=await realpath(await mkdtemp(join(tmpdir(),'pkw-cutover-files-')));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(join(root,'releases','new'),{recursive:true});await mkdir(join(root,'units'));const o={current:join(root,'current'),target:'releases/new',dropIn:join(root,'units','pkw.service.d','50-pkw-independent.conf')};o.content=independentDropIn({node:'/usr/local/bin/node',current:o.current,config:'/private/config.json'});return{root,o}}
test('first unit delta preserves original service and changes only owned drop-in and current',async t=>{const{root,o}=await fixture(t);await writeFile(join(root,'units','pkw.service'),'original');await installOwnedReferences(o);assert.equal(await readlink(o.current),'releases/new');assert.equal(await readFile(o.dropIn,'utf8'),o.content);assert.equal((await lstat(o.dropIn)).mode&0o777,0o644);await removeOwnedReferences(o);assert.deepEqual(await ownedReferences(o,'absent'),{current:false,dropIn:false});assert.equal(await readFile(join(root,'units','pkw.service'),'utf8'),'original')})
test('partial install after current creation can restore only owned references',async t=>{const{o}=await fixture(t);await assert.rejects(installOwnedReferences(o,{checkpoint:async n=>{if(n==='after-current')throw new Error('injected')}}));await removeOwnedReferences(o);assert.deepEqual(await ownedReferences(o,'absent'),{current:false,dropIn:false})})
test('unrelated current and changed drop-in are retained, never overwritten or deleted',async t=>{const{root,o}=await fixture(t);await symlink('releases/other',o.current);await assert.rejects(installOwnedReferences(o));assert.equal(await readlink(o.current),'releases/other');await rm(o.current);await installOwnedReferences(o);await writeFile(o.dropIn,'changed');await assert.rejects(removeOwnedReferences(o));assert.equal(await readlink(o.current),'releases/new');assert.equal(await readFile(o.dropIn,'utf8'),'changed')})
test('unit draft preserves environment-file references and only clears module/test injection flags',()=>{const s=independentDropIn({node:'/node',current:'/runtime/current',config:'/cfg.json'});assert.match(s,/ExecStart=\nExecStart=/);assert.match(s,/UnsetEnvironment=.*NODE_OPTIONS.*PKW_TEST_GATE_FILE/);assert.doesNotMatch(s,/EnvironmentFile|WEKNORA_API_KEY|PKW_BOOTSTRAP_PASSWORD|InaccessiblePaths|deepseek-harness|NODE_EXTRA_CA_CERTS/)})
test('atomic journals refuse exclusive replacement and leave unrelated symlinks unchanged',async t=>{const{root}=await fixture(t),p=join(root,'report.json');await writePrivateJson(p,{a:1},{exclusive:true});await assert.rejects(writePrivateJson(p,{a:2},{exclusive:true}));assert.deepEqual(JSON.parse(await readFile(p)),{a:1});await writePrivateJson(p,{a:3});assert.deepEqual(JSON.parse(await readFile(p)),{a:3});const q=join(root,'link');await symlink(p,q);await assert.rejects(writePrivateJson(q,{a:4}));assert.deepEqual(JSON.parse(await readFile(p)),{a:3})})
