/**
 * A synthetic Harness checkout, generated by the test itself.
 *
 * The profile builder resolves the PKW packages' Harness peers from a Harness *source
 * tree*. Testing it needed a private checkout, so CI either skipped it or failed. This
 * fixture writes the twelve peer packages the PKW manifest declares, with the entry
 * points the builder packs, so the closure can be resolved and the build exercised
 * anywhere — no private repository and no network.
 */
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

/** name -> { version, dir, files } for every peer the PKW packages declare. */
export const SYNTHETIC_PEERS = Object.freeze({
  '@deepseek-ai/cordis': { version: '4.0.1', dir: 'vendor/cordis', license: 'MIT' },
  '@deepseek-ai/cordis-plugin-timer': { version: '1.1.3', dir: 'vendor/timer' },
  '@deepseek-ai/schemastery': { version: '3.18.1', dir: 'vendor/schemastery' },
  '@deepseek-ai/cosmokit': { version: '1.8.2', dir: 'vendor/cosmokit' },
  '@deepseek-ai/dsh-fs': { version: '0.1.2-alpha.1', dir: 'packages/fs/fs' },
  '@deepseek-ai/dsh-fs-local': { version: '0.1.2-alpha.1', dir: 'packages/fs/fs-local' },
  '@deepseek-ai/dsh-host-webserver': { version: '0.1.2-alpha.1', dir: 'packages/host/webserver' },
  '@deepseek-ai/dsh-storage': { version: '0.1.2-alpha.1', dir: 'packages/storage/storage' },
  '@deepseek-ai/dsh-storage-domain': { version: '0.1.2-alpha.1', dir: 'packages/storage/storage-domain' },
  '@deepseek-ai/dsh-storage-sqlite': { version: '0.1.2-alpha.1', dir: 'packages/storage/storage-sqlite' },
  '@deepseek-ai/dsh-workspace': { version: '0.1.2-alpha.1', dir: 'packages/workspace/workspace' },
  '@deepseek-ai/dsh-brand': { version: '0.1.2-alpha.1', dir: 'packages/util/brand' },
  '@deepseek-ai/dsh-credentials': { version: '0.1.2-alpha.1', dir: 'packages/credentials/credentials' },
})

/**
 * Write a Harness-shaped tree and return its root.
 * Each package carries `lib/index.js` (the packed entry point) and re-exports the
 * packages it depends on, so importing the built profile actually links the closure.
 */
export async function makeSyntheticHarness(root) {
  const dir = root ?? await mkdtemp(join(tmpdir(), 'pkw-harness-'))
  // The caller may hand us a path that does not exist yet.
  await mkdir(dir, { recursive: true })
  await writeFile(join(dir, 'package.json'), JSON.stringify({
    name: '@deepseek-ai/dsh-root', version: '0.1.2-alpha.1', private: true, type: 'module',
  }, null, 2) + '\n')
  for (const [name, spec] of Object.entries(SYNTHETIC_PEERS)) {
    const pkgDir = join(dir, spec.dir)
    await mkdir(join(pkgDir, 'lib'), { recursive: true })
    const short = name.split('/')[1]
    // A dependency edge so the closure walk has something to follow, mirroring how the
    // real packages depend on each other.
    const dependsOn = spec.dir === 'packages/fs/fs' ? { '@deepseek-ai/dsh-brand': spec.version } : {}
    await writeFile(join(pkgDir, 'package.json'), JSON.stringify({
      name, version: spec.version, type: 'module', main: 'lib/index.js', files: ['lib'],
      ...(Object.keys(dependsOn).length ? { dependencies: dependsOn } : {}),
      ...(spec.license ? { license: spec.license } : {}),
    }, null, 2) + '\n')
    await writeFile(join(pkgDir, 'lib/index.js'), `// synthetic ${name}\nexport const name = ${JSON.stringify(name)}\nexport const version = ${JSON.stringify(spec.version)}\n`)
    await writeFile(join(pkgDir, 'lib/index.d.ts'), `export declare const name: string\nexport declare const version: string\n`)
  }
  return dir
}
